spring.application.name=splitwise

server.port=${PORT:9090}

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/splitwise
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.jpa.show-sql=true

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Redirect URI
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
